package com.of.ll.application.usecase;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import com.of.ll.domain.event.ActivitiesGeneratedEvent;
import com.of.ll.domain.filter.AgeFilter;
import com.of.ll.domain.filter.FilterPipeline;
import com.of.ll.domain.filter.SafetyFilter;
import com.of.ll.domain.filter.TimeFilter;
import com.of.ll.domain.filter.WeatherFilter;
import com.of.ll.domain.model.Activity;
import com.of.ll.domain.model.AgeRange;
import com.of.ll.domain.model.Context;
import com.of.ll.domain.model.Duration;
import com.of.ll.domain.model.LocationType;
import com.of.ll.domain.model.PreferredStyle;
import com.of.ll.domain.model.Season;
import com.of.ll.domain.model.Weather;
import com.of.ll.domain.scoring.ActivityTypeScoring;
import com.of.ll.domain.scoring.DefaultScoringPolicy;
import com.of.ll.domain.scoring.StepsScoring;
import com.of.ll.domain.scoring.TimeScoring;
import com.of.ll.domain.selector.TopActivitiesSelector;
import com.of.ll.doubles.FakeActivityGenerator;
import com.of.ll.doubles.FakeActivityHistoryRepository;
import com.of.ll.doubles.FakeTelemetryPort;
import com.of.ll.doubles.FakeUserPreferencesRepository;
import com.of.ll.port.out.Clock;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Unit tests for {@link GenerateDailyActivitiesUseCase}.
 *
 * <p>Tests verify the behavior of the daily activities generation use case, including:
 * <ul>
 * <li>Generation using primary activity generator</li>
 * <li>Fallback to secondary generator when primary returns empty results</li>
 * <li>Fallback when all primary activities are filtered out</li>
 * <li>Filtering and selection of top activities based on scoring policy</li>
 * <li>Telemetry event tracking for fallback usage</li>
 * </ul>
 *
 * <p>Uses a fixed context representing an urban summer environment with children aged 3-18
 * and 60 minutes of available time.
 */
class GenerateDailyActivitiesUseCaseTest {

    final FilterPipeline filterPipeline = new FilterPipeline(List.of(new AgeFilter(), new SafetyFilter(), new TimeFilter(10), new WeatherFilter()));
    final TopActivitiesSelector topActivitiesSelector = new TopActivitiesSelector(
            new DefaultScoringPolicy(List.of(new ActivityTypeScoring(), new StepsScoring(), new TimeScoring(10))));
    final Context context = new Context(UUID.randomUUID().toString(), LocationType.CITY, Season.SUMMER, Weather.SUN, 20,
            new AgeRange(3, 18), new Duration(60), PreferredStyle.OUTDOOR, null, List.of(), false);
    final Clock clock = Instant::now;

    /**
     * Verifies that the use case returns activities generated by the primary generator
     * when the generator provides valid activities.
     *
     * <p>Expected behavior:
     * <ul>
     * <li>Primary generator produces 3 sample activities</li>
     * <li>All activities pass through the filter pipeline</li>
     * <li>Top 3 activities are selected and returned</li>
     * <li>Telemetry event indicates primary generator was used (fallback = false)</li>
     * </ul>
     */
    @Nested
    class Generate {

        @Test
        void returnsActivitiesByPrimaryGenerator() {
            final FakeActivityGenerator aiGenerator = FakeActivityGenerator.withSampleActivities();
            final FakeActivityGenerator fallbackGenerator = FakeActivityGenerator.empty();
            final FakeTelemetryPort telemetryPort = new FakeTelemetryPort();
            final FakeActivityHistoryRepository historyRepository = new FakeActivityHistoryRepository();
            final FakeUserPreferencesRepository userPreferencesRepository = new FakeUserPreferencesRepository();

            final GenerateDailyActivitiesUseCase generateDailyActivitiesUseCase = new GenerateDailyActivitiesUseCase(aiGenerator, fallbackGenerator,
                    filterPipeline,
                    topActivitiesSelector, telemetryPort, clock, historyRepository, userPreferencesRepository);
            final List<Activity> result = generateDailyActivitiesUseCase.generate(context);

            assertEquals(3, result.size());
            final ActivitiesGeneratedEvent event = assertInstanceOf(ActivitiesGeneratedEvent.class, telemetryPort.lastEvent);
            assertFalse(event.fallbackUsed());
            assertEquals(1, historyRepository.saved.size());
        }

        @Test
        void returnsActivitiesByFallbackGenerator() {
            final FakeActivityGenerator aiGenerator = FakeActivityGenerator.empty();
            final FakeActivityGenerator fallbackGenerator = FakeActivityGenerator.withSampleActivities();
            final FakeTelemetryPort telemetryPort = new FakeTelemetryPort();
            final FakeActivityHistoryRepository historyRepository = new FakeActivityHistoryRepository();
            final FakeUserPreferencesRepository userPreferencesRepository = new FakeUserPreferencesRepository();

            final GenerateDailyActivitiesUseCase generateDailyActivitiesUseCase = new GenerateDailyActivitiesUseCase(aiGenerator, fallbackGenerator,
                    filterPipeline,
                    topActivitiesSelector, telemetryPort, clock, historyRepository, userPreferencesRepository);
            final List<Activity> result = generateDailyActivitiesUseCase.generate(context);

            assertEquals(3, result.size());
            final ActivitiesGeneratedEvent event = assertInstanceOf(ActivitiesGeneratedEvent.class, telemetryPort.lastEvent);
            assertTrue(event.fallbackUsed());
            assertEquals(1, historyRepository.saved.size());
        }

        @Test
        void returnsActivitiesByFallbackGeneratorWhenPrimariesAreFiltered() {
            final FakeActivityGenerator aiGenerator = FakeActivityGenerator.withSampleInvalidActivities();
            final FakeActivityGenerator fallbackGenerator = FakeActivityGenerator.withSampleActivities();
            final FakeTelemetryPort telemetryPort = new FakeTelemetryPort();
            final FakeActivityHistoryRepository historyRepository = new FakeActivityHistoryRepository();
            final FakeUserPreferencesRepository userPreferencesRepository = new FakeUserPreferencesRepository();

            final GenerateDailyActivitiesUseCase generateDailyActivitiesUseCase = new GenerateDailyActivitiesUseCase(aiGenerator, fallbackGenerator,
                    filterPipeline,
                    topActivitiesSelector, telemetryPort, clock, historyRepository, userPreferencesRepository);
            final List<Activity> result = generateDailyActivitiesUseCase.generate(context);

            assertEquals(3, result.size());
            final ActivitiesGeneratedEvent event = assertInstanceOf(ActivitiesGeneratedEvent.class, telemetryPort.lastEvent);
            assertTrue(event.fallbackUsed());
            assertEquals(1, historyRepository.saved.size());
        }
    }

}
